[0m08:07:49.759811 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f152ec6ec30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f153016a750>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f152ef6bd10>]}


============================== 08:07:49.762700 | 559f1bb8-655f-4a13-8db9-4408af2fddf6 ==============================
[0m08:07:49.762700 [info ] [MainThread]: Running with dbt=1.8.7
[0m08:07:49.763142 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': '/opt/dbt', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt debug', 'send_anonymous_usage_stats': 'True'}
[0m08:07:49.773282 [info ] [MainThread]: dbt version: 1.8.7
[0m08:07:49.773765 [info ] [MainThread]: python version: 3.12.6
[0m08:07:49.774106 [info ] [MainThread]: python path: /opt/bitnami/python/bin/python
[0m08:07:49.774428 [info ] [MainThread]: os info: Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.36
[0m08:07:49.923312 [info ] [MainThread]: Using profiles dir at /opt/dbt
[0m08:07:49.923867 [info ] [MainThread]: Using profiles.yml file at /opt/dbt/profiles.yml
[0m08:07:49.924259 [info ] [MainThread]: Using dbt_project.yml file at /opt/dbt/dbt_project.yml
[0m08:07:49.924850 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m08:07:49.926140 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_wall_clock_time": 0.21430446, "process_user_time": 1.2545, "process_kernel_time": 0.099563, "process_mem_max_rss": "93912", "process_in_blocks": "8", "process_out_blocks": "8", "command_success": false}
[0m08:07:49.926802 [debug] [MainThread]: Command `dbt debug` failed at 08:07:49.926689 after 0.22 seconds
[0m08:07:49.927428 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f152ecc88c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f152f42cce0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f152ec9f350>]}
[0m08:07:49.928059 [debug] [MainThread]: Flushing usage events
